---
title: "Phylosignal analysis - multiple simulations"
---


```{r}
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(igraph)
library(EnvStats)
library(aricode)
library(vegan)
library(ade4)
library(ape)
library(tidyr)
library(ggraph)
library(purrr)
library(mclust)  # for ARI
library(clue)    # for NMI

source(here::here("code/functions/functions_simulation.R")) 
source(here::here("code/functions/function_to_phylo.R")) 
#source(here::here("code/functions/function_compute_decomposed_matrices.R")) # it works for al the phylosign analyses

#source(here::here("code/functions/function_compute_decomposed_matrices.R"))
source(here::here("code/functions/function_compute_decomposed_matrices_17may.R"))

source(here::here("code/functions/functions_compute_signal_23may.R"))
```



## compute decomposed matrices for each simulation (and save them)

```{r}

#dir.create("decomposed_matrices", showWarnings = FALSE)

files <- list.files("simulations/neutral/test", full.names = TRUE, pattern = "res_sim_\\d+\\.rds")

for (i in seq_along(files)) {
  
  cat("analyzing simulation ", i)
  
  res_sim <- readRDS(files[i])
  
  sdv_matrices <- compute_decomposed_matrices_roles(
    results_simulation = res_sim,
    int = "foodweb",
    Smax = 1000,
    nbasals = 5
  )
  
  saveRDS(sdv_matrices, file = file.path("decomposed_matrices/neutral/test", paste0("sdv_matrices_roles_", i, ".rds")))
}


```



# PROCRUSTES


```{r}

decomposed_files <- list.files("decomposed_matrices/selection/test", full.names = TRUE, pattern = "sdv_matrices_roles_\\d+\\.rds")

all_procrustes_results <- list()

for (i in seq_along(decomposed_files)) {
  cat("Processing decomposed simulation", i, "\n")
  sdv_matrices <- readRDS(decomposed_files[i])
  
  result <- compute_procrustes_signal_roles(sdv_matrices)
  result$simulation <- i
  all_procrustes_results[[i]] <- result
}

df_all_procrustes <- bind_rows(all_procrustes_results)

#saveRDS(df_all_procrustes, here::here("output/selection/test/selection_df_all_procrustes.rds"))
df_all_procrustes <- readRDS(here::here("output/selection/test/selection_df_all_procrustes.rds"))

```


```{r}
summary_df <- df_all_procrustes %>%
  group_by(role, timestep) %>%
  summarize(
    mean_cor = mean(cor, na.rm = TRUE),
    sd_cor = sd(cor, na.rm = TRUE),
    .groups = "drop"
  )

# mean timestep where max. S is reached:

mean_timestep_s60 <- df_all_procrustes %>%
  filter(S == 60) %>%
  summarise(mean_ts = mean(timestep, na.rm = TRUE)) %>%
  pull(mean_ts)


ggplot(summary_df, aes(x = timestep, y = mean_cor, color = role, fill = role)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = mean_cor - sd_cor, ymax = mean_cor + sd_cor), alpha = 0.3, color = NA) +
  geom_vline(xintercept = mean_timestep_s60, linetype = "dashed", color = "black") +
  labs(
    x = "Timestep",
    y = "Procrustes correlation",
    title = "Procrustes signal: predators vs prey vs both"
  ) +
  scale_color_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  scale_fill_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  theme_minimal() +
  ylim(0, 1)


```


```{r}
# summary_df <- df_all %>%
#   group_by(role, S) %>%
#   summarize(
#     mean_cor = mean(cor, na.rm = TRUE),
#     sd_cor = sd(cor, na.rm = TRUE),
#     .groups = "drop"
#   )
# 
# ggplot(summary_df, aes(x = S, y = mean_cor, color = role, fill = role)) +
#   geom_line(size = 1) +
#   geom_ribbon(aes(ymin = mean_cor - sd_cor, ymax = mean_cor + sd_cor), alpha = 0.3, color = NA) +
#   labs(
#     x = "Timestep",
#     y = "Procrustes correlation",
#     title = "Procrustes signal: predators vs prey vs both"
#   ) +
#   scale_color_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
#   scale_fill_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
#   theme_minimal() +
#   ylim(0, 1)
```



# MANTEL


STORE DATA

```{r}
decomposed_files <- list.files("decomposed_matrices/selection/test", full.names = TRUE, pattern = "sdv_matrices_roles_\\d+\\.rds")

all_mantel_results <- list()

for (i in seq_along(decomposed_files)) {
  cat("Processing decomposed simulation", i, "\n")
  sdv_matrices <- readRDS(decomposed_files[i])
  
  result <- compute_mantel_signal_roles(sdv_matrices)
  result$simulation <- i
  all_mantel_results[[i]] <- result
}

df_mantel <- bind_rows(all_mantel_results)

saveRDS(df_mantel, here::here("output/selection/test/selectio_df_mantel_1-61.rds"))

```



```{r}
summary_mantel <- df_mantel %>%
  group_by(role, timestep) %>%
  summarize(
    mean_cor = mean(cor_mantel, na.rm = TRUE),
    sd_cor = sd(cor_mantel, na.rm = TRUE),
    .groups = "drop"
  )

# mean timestep for max. S is reached

mean_timestep_s60 <- df_mantel %>%
  filter(S == 60) %>%
  summarise(mean_ts = mean(timestep, na.rm = TRUE)) %>%
  pull(mean_ts)


ggplot(summary_mantel, aes(x = timestep, y = mean_cor, color = role, fill = role)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = mean_cor - sd_cor, ymax = mean_cor + sd_cor), alpha = 0.2, color = NA) +
  geom_vline(xintercept = mean_timestep_s60, linetype = "dashed", color = "black") +
  labs(
    x = "Timestep",
    y = "Mantel correlation",
    color = "Role",
    fill = "Role"
  ) +
  scale_color_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  scale_fill_manual(values = c("pred" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  theme_minimal() +
  ylim(0, 1)

```



# JACCARD



```{r}
decomposed_files <- list.files("decomposed_matrices/selection/test1", full.names = TRUE, pattern = "sdv_matrices_roles_\\d+\\.rds")

jaccard_results <- purrr::map_dfr(seq_along(decomposed_files), function(i) {
  cat("Analyzing simulation", i, "\n")
  sdv <- readRDS(decomposed_files[i])
  df <- compute_jaccard_phylo_correlation(sdv)
  if (nrow(df) > 0) {
    df$sim <- i
  }
  return(df)
})


#saveRDS(jaccard_results, here::here("output/selection/selection_jaccard_results.rds"))

```

```{r}
jaccard_long <- jaccard_results %>%
  pivot_longer(cols = c(predator, prey, both), names_to = "role", values_to = "correlation") %>%
  mutate(correlation = abs(correlation))  # <-- TAKE ABSOLUTE VALUE here

summary_jaccard <- jaccard_long %>%
  group_by(role, timestep) %>%
  summarize(
    mean_cor = mean(correlation, na.rm = TRUE),
    sd_cor = sd(correlation, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(summary_jaccard, aes(x = timestep, y = mean_cor, color = role, fill = role)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = mean_cor - sd_cor, ymax = mean_cor + sd_cor), alpha = 0.2) +
  labs(
    x = "Timestep",
    y = "Absolute Jaccard-Phylo correlation",
    color = "Role",
    fill = "Role"
  ) +
  scale_color_manual(values = c("predator" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  scale_fill_manual(values = c("predator" = "steelblue", "prey" = "tomato", "both" = "darkgreen")) +
  theme_minimal() +
  ylim(0, 1)


```


# CLUSTERS


```{r}
decomposed_files <- list.files("decomposed_matrices/neutral/test", full.names = TRUE, pattern = "sdv_matrices_roles_\\d+\\.rds")

decomposed_files <- decomposed_files[1:10]

all_cluster_results <- map_dfr(seq_along(decomposed_files), function(i) {
  cat("Analyzing simulation", i, "\n")
  sdv <- readRDS(decomposed_files[i])
  res_sim <- readRDS(list.files("simulations/neutral/test", full.names = TRUE, pattern = "res_sim_\\d+\\.rds")[i])
  
  metrics <- compute_clustering_metrics_roles(sdv_matrices = sdv, results_simulation = res_sim)

  metrics$sim <- i
  return(metrics)
})

#saveRDS(all_cluster_results, here::here("output/neutral/test/neutral_all_cluster_results.rds"))

```

```{r}

summary_cluster <- all_cluster_results %>%
  group_by(timestep) %>%
  summarise(
    mean_VI = mean(VI, na.rm = TRUE),
    sd_VI = sd(VI, na.rm = TRUE),
    mean_NMI = mean(NMI, na.rm = TRUE),
    sd_NMI = sd(NMI, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(!is.nan(mean_VI) | !is.nan(mean_NMI))  # remove completely missing rows


summary_long <- summary_cluster %>%
  pivot_longer(
    cols = c(mean_VI, mean_NMI, sd_VI, sd_NMI),
    names_to = c(".value", "metric"),
    names_pattern = "(.+)_(VI|NMI)"
  )

# Plot with legend
ggplot(summary_long, aes(x = timestep, color = metric, fill = metric)) +
  geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd), alpha = 0.2, color = NA) +
  geom_line(aes(y = mean), size = 1) +
  labs(x = "Timestep", y = "Metric value", title = "Mean VI and NMI with variance") +
  scale_color_manual(values = c(VI = "blue", NMI = "red")) +
  scale_fill_manual(values = c(VI = "blue", NMI = "red")) +
  theme_minimal() +
  theme(legend.position = "right")

```





